import { execFileSync } from "child_process";
import manifest from "../../content-dates.json";

// Content "last modified" / "first published" dates for JSON-LD and the
// sitemap, resolved from a COMMITTED MANIFEST rather than from the build
// environment.
//
// History, because the shape of this file is a scar and should stay legible:
//
//  1. It used `fs.statSync().mtime`. A fresh CI checkout resets mtimes to the
//     deploy time, so every page claimed to have changed on every deploy.
//  2. It shelled out to `git log`, which is correct and stable across
//     checkouts. That worked locally and silently did not work on Railway: the
//     deployed site served hardcoded fallback dates for weeks while the content
//     was corrected repeatedly, so to a crawler nothing had changed since
//     2026-07-25. The build was green the whole time, because a wrong date is
//     not a compile error. Reproduced on 2026-08-02 by building with git off
//     PATH, which emits exactly the dates production was serving.
//  3. Adding `git` to the build image (nixpacks.toml) did NOT fix it, and the
//     real cause is not observable from outside Railway's build logs.
//
// So the build no longer asks the container anything. `content-dates.json` is
// generated by `npm run dates` on a machine that has git and full history,
// committed as data, and IMPORTED here rather than read through `fs`, so it is
// bundled into the build and cannot depend on cwd, on file tracing, or on what
// the image happens to contain. `npm run check:dates` fails when it goes stale.
//
// The git path below survives only as a local-development convenience for a
// path the manifest has not caught up with yet. Production never needs it.

type Manifest = { generated: string; modified: Record<string, string>; created: Record<string, string> };
const DATES = manifest as Manifest;

const ISO = /^\d{4}-\d{2}-\d{2}$/;

/** Which source answered, for the /api/health provenance block. */
export type DateSource = "manifest" | "git" | "fallback";
const used: Record<DateSource, number> = { manifest: 0, git: 0, fallback: 0 };

/**
 * Does the SHIPPED manifest carry a usable date for this path?
 *
 * This is the question /api/health actually needs to answer, and the counters
 * below cannot answer it. Every page is prerendered during `next build`, in a
 * different process from the one serving traffic, so the running server's
 * counters only ever record the health route's own lookups: they would read
 * `{manifest: N, fallback: 0}` on a deploy whose pages had all fallen back.
 * A counter that cannot go red is not provenance. This can.
 */
export function manifestHas(pathOrRel: string): boolean {
  const v = DATES.modified?.[relKey(pathOrRel)];
  return Boolean(v && ISO.test(v));
}

export function dateProvenance() {
  return {
    manifestGenerated: DATES.generated ?? null,
    manifestEntries: Object.keys(DATES.modified ?? {}).length,
    // Renamed from `resolvedFrom`, which read like a build-wide tally and was
    // one: a per-process lookup count, almost entirely from this endpoint.
    lookupsThisProcess: { ...used },
  };
}

// Call sites pass either form: the markdown-backed routes build an ABSOLUTE
// path with path.join(process.cwd(), ...), while the sitemap passes
// repo-relative strings. git accepted both, so the difference never mattered
// and the two styles coexist. A plain object lookup does not, and keying the
// manifest on absolute paths would bake this machine's home directory into a
// committed file. So normalise here: strip the cwd prefix and look up the
// repo-relative key the manifest actually holds.
//
// Caught by fault-injecting a git-less build, where /hearings and /notes fell
// through to fallbacks while every sitemap entry resolved correctly. Without
// git underneath to paper over it, the mismatch was finally visible.
function relKey(pathOrRel: string): string {
  const cwd = process.cwd();
  if (pathOrRel.startsWith(cwd)) {
    return pathOrRel.slice(cwd.length).replace(/^[/\\]/, "");
  }
  return pathOrRel;
}

export function contentDate(pathOrRel: string, fallback: string): string {
  const key = relKey(pathOrRel);
  return resolve(DATES.modified?.[key], ["log", "-1", "--format=%as", "--", pathOrRel], fallback, key);
}

export function contentCreatedDate(pathOrRel: string, fallback: string): string {
  const key = relKey(pathOrRel);
  return resolve(
    DATES.created?.[key],
    ["log", "--diff-filter=A", "--follow", "-1", "--format=%as", "--", pathOrRel],
    fallback,
    key,
  );
}

function resolve(fromManifest: string | undefined, gitArgs: string[], fallback: string, p: string): string {
  if (fromManifest && ISO.test(fromManifest)) {
    used.manifest++;
    return fromManifest;
  }
  const fromGit = gitDate(gitArgs);
  if (fromGit) {
    used.git++;
    return fromGit;
  }
  used.fallback++;
  warnOnce(p);
  return fallback;
}

function gitDate(args: string[]): string | null {
  try {
    const out = execFileSync("git", args, {
      cwd: process.cwd(),
      encoding: "utf-8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return ISO.test(out) ? out : null;
  } catch {
    return null;
  }
}

// The original defect was not that dates were wrong, it was that being wrong
// looked exactly like being right. Falling back stays non-fatal (one missing
// date must not fail a deploy) but never stays quiet.
//
// "Once" means once per worker process, not once per build: Next renders static
// pages across ~15 workers, each with its own module instance, so a broken
// build prints this roughly ten times. That is louder than intended and the
// right trade for a message whose whole job is to be impossible to miss.
let warned = false;
function warnOnce(p: string): void {
  if (warned) return;
  warned = true;
  console.warn(
    `\n[contentDate] "${p}" is in neither content-dates.json nor git; using a hardcoded fallback.\n` +
      `[contentDate] Dates in this build are literals, not real content dates, so the site will ` +
      `look unchanged to crawlers. Run \`npm run dates\` and commit content-dates.json.\n`,
  );
}
